services:
  db:
    image: mariadb:latest
    container_name: mysql-db-only
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_employee
      MYSQL_USER: root
      MYSQL_PASSWORD: password_go
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
